const [
    INCREMENT, DECREMENT, 
    INCREMENT_ASYNC, DECREMENT_ASYNC
] = [ 
    'INCREMENT', 'DECREMENT', 
    'INCREMENT_ASYNC', 'DECREMENT_ASYNC'
];

export { 
    INCREMENT, DECREMENT, 
    INCREMENT_ASYNC, DECREMENT_ASYNC
};